[package]
name = "rimsort-rs"
version.workspace = true
edition.workspace = true
license.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
rimsort-core = { path = "../crates/rimsort-core" }
serde = { version = "1.0.229", features = ["derive"] }
specta = "=2.0.0-rc.25"
specta-typescript = "=0.0.12"
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
tauri-plugin-single-instance = "2"
tauri-plugin-window-state = "2"
tauri-specta = { version = "=2.0.0-rc.25", features = ["derive", "typescript"] }
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[target.'cfg(windows)'.dependencies]
steamworks = "0.13.1"
