// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	ping: () => __TAURI_INVOKE<string>("ping"),
	/**  Frontend console/error sink so UI problems land in the same log file. */
	logFrontend: (level: string, message: string) => __TAURI_INVOKE<void>("log_frontend", { level, message }),
	getSettings: () => typedError<SettingsView, ErrorDto>(__TAURI_INVOKE("get_settings")),
	saveInstance: (instance: InstanceDto) => typedError<null, ErrorDto>(__TAURI_INVOKE("save_instance", { instance })),
	updateOptions: (options: OptionsDto) => typedError<null, ErrorDto>(__TAURI_INVOKE("update_options", { options })),
	switchInstance: (name: string) => typedError<null, ErrorDto>(__TAURI_INVOKE("switch_instance", { name })),
	createInstance: (name: string) => typedError<null, ErrorDto>(__TAURI_INVOKE("create_instance", { name })),
	deleteInstance: (name: string) => typedError<null, ErrorDto>(__TAURI_INVOKE("delete_instance", { name })),
	autodetectPaths: () => typedError<DetectedPaths, ErrorDto>(__TAURI_INVOKE("autodetect_paths")),
	/**  Scan mods + read ModsConfig.xml in the background; refetch lists on the task's `finished` event. */
	startScan: () => typedError<number, ErrorDto>(__TAURI_INVOKE("start_scan")),
	getLists: () => typedError<ListsView, ErrorDto>(__TAURI_INVOKE("get_lists")),
	getMod: (id: ModId) => typedError<{
	id: ModId,
	name: string,
	package_id: string,
	authors: string[],
	description: string,
	path: string,
	url: string,
	mod_version: string,
	supported_versions: string[],
	mod_type: ModType,
	valid: boolean,
	invalid_reason: string | null,
	published_file_id: string | null,
	dependencies: string[],
	load_after: string[],
	load_before: string[],
	incompatible_with: string[],
	/**  Absolute path of `About/Preview.png` when it exists. */
	preview: string | null,
	color: string | null,
	tags: string[],
	note: string,
} | null, ErrorDto>(__TAURI_INVOKE("get_mod", { id })),
	setActive: (ids: ModId[]) => typedError<null, ErrorDto>(__TAURI_INVOKE("set_active", { ids })),
	getValidation: () => typedError<ValidationView, ErrorDto>(__TAURI_INVOKE("get_validation")),
	createLocalCopy: (id: ModId) => typedError<number, ErrorDto>(__TAURI_INVOKE("create_local_copy", { id })),
	listBackups: () => typedError<BackupInfo[], ErrorDto>(__TAURI_INVOKE("list_backups")),
	cloneGitMods: (urls: string[]) => typedError<number, ErrorDto>(__TAURI_INVOKE("clone_git_mods", { urls })),
	downloadMods: (ids: string[]) => typedError<number, ErrorDto>(__TAURI_INVOKE("download_mods", { ids })),
	updateDatabases: () => typedError<DbResult[], ErrorDto>(__TAURI_INVOKE("update_databases")),
	updateGitMod: (id: ModId) => typedError<string, ErrorDto>(__TAURI_INVOKE("update_git_mod", { id })),
	setModMeta: (id: ModId, meta: MetaDto) => typedError<null, ErrorDto>(__TAURI_INVOKE("set_mod_meta", { id, meta })),
	deleteMod: (id: ModId) => typedError<null, ErrorDto>(__TAURI_INVOKE("delete_mod", { id })),
	getDuplicates: () => typedError<DupGroup[], ErrorDto>(__TAURI_INVOKE("get_duplicates")),
	getModRules: (id: ModId) => typedError<{
	package_id: string,
	name: string,
	about_load_after: string[],
	about_load_before: string[],
	community_load_after: string[],
	community_load_before: string[],
	community_top: boolean,
	community_bottom: boolean,
	user: UserRuleDto,
	/**  Warnings suppressed for this mod (`ignore.json`). */
	ignored: boolean,
} | null, ErrorDto>(__TAURI_INVOKE("get_mod_rules", { id })),
	setUserRule: (id: ModId, rule: UserRuleDto) => typedError<null, ErrorDto>(__TAURI_INVOKE("set_user_rule", { id, rule })),
	setIgnored: (id: ModId, ignored: boolean) => typedError<null, ErrorDto>(__TAURI_INVOKE("set_ignored", { id, ignored })),
	getMissingDependencies: () => typedError<MissingDep[], ErrorDto>(__TAURI_INVOKE("get_missing_dependencies")),
	sortActive: () => typedError<SortResultDto, ErrorDto>(__TAURI_INVOKE("sort_active")),
	saveModsConfig: () => typedError<SaveResult, ErrorDto>(__TAURI_INVOKE("save_mods_config")),
	importModlist: (path: string) => typedError<ImportResult, ErrorDto>(__TAURI_INVOKE("import_modlist", { path })),
	exportModlist: (path: string, format: ExportFormat) => typedError<null, ErrorDto>(__TAURI_INVOKE("export_modlist", { path, format })),
	exportModlistText: (format: ExportFormat) => typedError<string, ErrorDto>(__TAURI_INVOKE("export_modlist_text", { format })),
	readPlayerLog: (offset: number | null) => typedError<LogChunk, ErrorDto>(__TAURI_INVOKE("read_player_log", { offset })),
	launchGame: () => typedError<null, ErrorDto>(__TAURI_INVOKE("launch_game")),
	cancelTask: (id: number) => typedError<null, ErrorDto>(__TAURI_INVOKE("cancel_task", { id })),
};

/** Events */
export const events = {
	taskUpdate: makeEvent<TaskUpdate>("task-update"),
};

/* Types */
export type BackupInfo = {
	path: string,
	unix: number,
	count: number,
};

export type DbResult = {
	name: string,
	status: DbStatus,
	/**  Error text when `Failed`, else size info. */
	detail: string,
};

export type DbStatus = "Updated" | "NotModified" | "Failed";

export type DetectedPaths = {
	game_folder: string | null,
	config_folder: string | null,
	local_folder: string | null,
	workshop_folder: string | null,
	/**  Human-readable explanation of what was/wasn't found. */
	notes: string[],
};

/**  One installed copy of a package that exists in several places. */
export type DupCopy = {
	id: ModId,
	path: string,
	mod_type: ModType,
	published_file_id: string | null,
	mod_version: string,
	/**  This copy is the one currently in the active list. */
	active: boolean,
};

export type DupGroup = {
	package_id: string,
	name: string,
	copies: DupCopy[],
};

/**  UI-facing error: `{ kind, message }`. Commands return `Result<T, ErrorDto>`. */
export type ErrorDto = {
	kind: string,
	message: string,
};

export type ExportFormat = 
/**  RimWorld `ModsConfig.xml` layout. */
"Xml" | 
/**  RimSort JSON (`version`, `activeMods`, `knownExpansions`). */
"Json" | 
/**  One package id per line. */
"PackageIds" | 
/**  Human-readable `Name [package.id][url]` report. */
"Report";

export type ImportResult = {
	/**  Entries resolved to installed mods and now active. */
	imported: number,
	/**  Package ids in the file that aren't installed. */
	missing: string[],
};

export type InstanceDto = {
	name: string,
	game_folder: string,
	config_folder: string,
	local_folder: string,
	workshop_folder: string,
	run_args: string,
	/**  Launch through the Steam client instead of the game executable. */
	launch_via_steam: boolean,
};

export type ListsView = {
	active: ModRow[],
	inactive: ModRow[],
	/**  Package ids in `ModsConfig.xml` that aren't installed. */
	missing: string[],
	game_version: string,
	scan_ms: number,
	duplicate_package_ids: number,
	/**  Entries loaded from the community / user rules databases (0 = not found). */
	community_rules: number,
	user_rules: number,
};

export type LogChunk = {
	path: string,
	text: string,
	/**  Pass back as `offset` on the next read. */
	offset: number,
	/**  Replace the displayed log instead of appending. */
	reset: boolean,
};

/**  Personal color/tags/note for a mod. */
export type MetaDto = {
	color: string | null,
	tags: string[],
	note: string,
};

/**  A required package that isn't active, aggregated over everything that needs it. */
export type MissingDep = {
	package_id: string,
	name: string,
	workshop_id: string | null,
	/**  Names of active mods that require it. */
	required_by: string[],
	/**  An installed (but inactive) mod that satisfies it. */
	installed: ModId | null,
};

export type ModDetail = {
	id: ModId,
	name: string,
	package_id: string,
	authors: string[],
	description: string,
	path: string,
	url: string,
	mod_version: string,
	supported_versions: string[],
	mod_type: ModType,
	valid: boolean,
	invalid_reason: string | null,
	published_file_id: string | null,
	dependencies: string[],
	load_after: string[],
	load_before: string[],
	incompatible_with: string[],
	/**  Absolute path of `About/Preview.png` when it exists. */
	preview: string | null,
	color: string | null,
	tags: string[],
	note: string,
};

/**  Stable mod identity: uuid5 of the mod folder path, same across scans. */
export type ModId = string;

/**  Compact list row; full detail is fetched with `get_mod`. */
export type ModRow = {
	id: ModId,
	name: string,
	authors: string,
	package_id: string,
	mod_type: ModType,
	valid: boolean,
	unsupported_version: boolean,
	published_file_id: string | null,
	/**  Folder modification time, Unix seconds (0 when unknown). */
	modified: number,
	/**  User-chosen color (`#rrggbb`). */
	color: string | null,
	tags: string[],
	has_note: boolean,
};

/**  All rule sources for one mod, for the rule editor. */
export type ModRulesView = {
	package_id: string,
	name: string,
	about_load_after: string[],
	about_load_before: string[],
	community_load_after: string[],
	community_load_before: string[],
	community_top: boolean,
	community_bottom: boolean,
	user: UserRuleDto,
	/**  Warnings suppressed for this mod (`ignore.json`). */
	ignored: boolean,
};

export type ModType = "Local" | "SteamWorkshop" | "SteamCmd" | "Ludeon" | "Git" | "Unknown";

export type ModWarnings = {
	id: ModId,
	warnings: Warning[],
};

/**  Global toggles that affect scanning, sorting and validation. */
export type OptionsDto = {
	/**  Treat declared `modDependencies` as implicit loadAfter rules when sorting. */
	dependencies_as_load_after: boolean,
	/**  Let a dependency's alternative package ids satisfy it. */
	use_alternative_ids: boolean,
	/**  Prefer `*ByVersion` About.xml entries for the running game version (applied on rescan). */
	prefer_versioned: boolean,
};

export type PathCheck = {
	kind: string,
	path: string,
	ok: boolean,
	reason: string,
};

export type SaveResult = {
	path: string,
	backup: string | null,
	count: number,
};

export type SettingsView = {
	current_instance: string,
	instances: InstanceDto[],
	sorting_algorithm: string,
	options: OptionsDto,
	/**  Set when settings were corrupt and reset this launch. */
	warning: string | null,
	checks: PathCheck[],
	game_version: string,
};

export type SortResultDto = {
	ok: boolean,
	/**  Package-id cycles when `ok` is false. */
	cycles: string[][],
	changed: boolean,
};

export type TaskEvent = { kind: "progress"; id: number; done: number; total: number; msg: string } | { kind: "finished"; id: number } | { kind: "cancelled"; id: number } | { kind: "failed"; id: number; error: ErrorDto } | 
/**  Not a task: files changed outside the app (`what` = "mods" | "config"). Shares this channel. */
{ kind: "fs_changed"; what: string };

/**  Emitted for every task state change (`task://` in the plan; one typed event carrying a tagged enum). */
export type TaskUpdate = TaskEvent;

/**  User-editable rules for one mod (stored in `userRules.json`). */
export type UserRuleDto = {
	load_after: string[],
	load_before: string[],
	load_top: boolean,
	load_bottom: boolean,
};

export type ValidationView = {
	/**  Only mods that have at least one warning. */
	mods: ModWarnings[],
	/**  Mods with an error-level warning. */
	errors: number,
	/**  Mods with only warning-level issues. */
	warnings: number,
	/**  Distinct packages required but not active. */
	missing_dependencies: number,
};

export type Warning = {
	kind: WarningKind,
	other: string,
	other_name: string,
};

export type WarningKind = 
/**  `other` is a required package that isn't active. */
"MissingDependency" | 
/**  `other` is an active mod declared incompatible (by either side). */
"Incompatible" | 
/**  This mod should load before `other`, but comes after it. */
"LoadBefore" | 
/**  This mod should load after `other`, but comes before it. */
"LoadAfter" | 
/**  Mod doesn't list support for the running game version. */
"VersionMismatch" | 
/**  A maintained replacement exists: `other` = its Workshop id, `other_name` = "Name by Author". */
"UseThisInstead";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

