[package]
name = "rimsort-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
specta = { version = "=2.0.0-rc.25", features = ["derive", "uuid"] }
thiserror = "2"
uuid = { version = "1", features = ["v5", "serde"] }
serde_json = "1"
encoding_rs = "0.8"
rayon = "1"
dirs = "7"
petgraph = "0.8"
natord = "1"
tracing = "0.1"
notify = "8.2.0"
notify-debouncer-mini = "0.7.0"
trash = "5.2.9"
rusqlite = { version = "0.40.2", features = ["bundled"] }
flate2 = "1.1.10"
reqwest = { version = "0.13.5", default-features = false, features = ["blocking", "rustls"] }
zip = { version = "8.6.0", default-features = false, features = ["deflate"] }
tar = "0.4.46"
sysinfo = { version = "0.39.6", default-features = false, features = ["system"] }
regex = "1.13.1"

[target.'cfg(windows)'.dependencies]
winreg = "0.56"

[dev-dependencies]
tempfile = "3"
